export const AppImages = {
  COOKING: require('../assets/images/cooking.png'),
  DRINKING: require('../assets/images/drinking.png'),
  EXERCISE: require('../assets/images/exercise.png'),
  FOOD_SET_ONE: require('../assets/images/food_set_one.png'),
  FOOD_SET_TWO: require('../assets/images/food_set_two.png'),
  FOOD: require('../assets/images/food.png'),
  LOGO: require('../assets/images/logo.png'),
  MEAL_PLANNER_LANDING: require('../assets/images/meal_planner_landing.png'),
  MEDITATION: require('../assets/images/meditation.png'),
  ORANGE_CHAT: require('../assets/images/orange_chat.png'),
  PURPLE_CHAT: require('../assets/images/purple_chat.png'),
  RUNNING: require('../assets/images/running.png'),
  STROKE_SET_ONE: require('../assets/images/stroke_set_one.png'),
  STROKE_SET_TWO: require('../assets/images/stroke_set_two.png'),
  USER: require('../assets/images/user.png'),
  WALK: require('../assets/images/walk.png'),
  WALING: require('../assets/images/walking.png'),
  GOOGLE_ICON: require('../assets/images/google_icon.png'),
  INACTIVE_MEAL: require('../assets/images/tabNavigator/inactive_meal.png'),
  INACTIVE_GYM: require('../assets/images/tabNavigator/inactive_gym.png'),
  ACTIVE_MEAL: require('../assets/images/tabNavigator/active_meal.png'),
  ACTIVE_GYM: require('../assets/images/tabNavigator/active_gym.png'),
  MASTER_CARD: require('../assets/images/master_card.png'),
  WORKOUT_LANDING_HEADER: require('../assets/images/workout_landing_header.png'),
};
